# Generated by Django 4.0.5 on 2022-07-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
    ]
